// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhichCloud.Web.data;

namespace WhichCloud.Web.Migrations
{
    [DbContext(typeof(ResourceContext))]
    [Migration("20200505164012_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("WhichCloud.Web.Models.VM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Bandwidth")
                        .HasColumnType("REAL");

                    b.Property<int>("CPU")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<int>("Memory")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<int>("Storage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VMTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VMTypeId");

                    b.ToTable("VMs");
                });

            modelBuilder.Entity("WhichCloud.Web.Models.VMType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VMTypes");
                });

            modelBuilder.Entity("WhichCloud.Web.Models.VM", b =>
                {
                    b.HasOne("WhichCloud.Web.Models.VMType", "VMType")
                        .WithMany()
                        .HasForeignKey("VMTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
